### PR TITLE
CI build

### PR DESCRIPTION
**Pull request by OwnageIsMagic**

### CODE REVIEW

**Comment by dail8859** [comment]
For such a small project I don't really see it adding much value. Also, since it isn't building *this* repo (i.e dail885/LuaScript) then technically it can't be guaranteed it is actually passing.

**Comment by OwnageIsMagic** [comment]
Actually it builds this repo (dail885/LuaScript)
but cause is not my repo it can't setup webhooks for auto build
The main feature that I don't need to ask you for new dev build for me or forcing you to publish new version
There is already 51 commit passed since last release

**Comment by dail8859** [comment]
> Actually it builds this repo (dail885/LuaScript)

It seems to build a fork of this repo which may or may not be behind this repo's current HEAD. You are certainly more than welcome to use CI for building a dev version for yourself.

FYI I'm hoping to do a new release before too long.

**Comment by OwnageIsMagic** [comment]
I'm quit sure that it builds this repo
image
latest build
image
and my fork HEAD
image

**Comment by dail8859** [comment]
Ok...so what did you mean by:

> but cause it's not my repo it can't setup webhooks for auto build

**Comment by OwnageIsMagic** [comment]
image

**Comment by dail8859** [comment]
How does CI know to rebuild if it doesn't receive webhooks from my repository?

**Comment by OwnageIsMagic** [comment]
upd

**Comment by dail8859** [comment]
> only when I manually trigger

Ah ok this is the part I wasn't understanding. I didn't know it could be manually triggered.

So this still gets back to the issue of the status may or may not be representative of my repository's current HEAD. Meaning its possible that:

- I push a new change.
- There is a delay (possibly several minutes, hours, days) until you manually trigger it.
- Then the badge is updated to the represent the current build status.

Like you said the build should always be passing so honestly no one else probably cares if it is passing or not. Again you are welcome to use CI for yourself but the badge in the readme doesn't benefit the project anything.

**Pull request closed without merging**
