### PR TITLE
Update LuaSyntaxChecker.lua

### PR DESCRIPTION
**Pull request by OwnageIsMagic**
add colors to error msg

### CODE REVIEW

**Comment by dail8859** [comment]
Awesome! Just curious, is there a particular benefit to check the returned error messages as opposed to the returned function?

**Comment by OwnageIsMagic** [comment]
Because we check for errors in code, eh?

**Comment by dail8859** [comment]
That doesn't tell me if there is a benefit though. The official documentation for `load()` states:

> If there are no syntactic errors, returns the compiled chunk as a function; otherwise, returns nil plus the error message. 

I'm fine either way. I was just curious.

**Comment by OwnageIsMagic** [comment]
Checking for error is semantically _(is this right word?)_ clearer to show what are we doing

**Comment by dail8859** [comment]
Thanks! 👍

**Pull request merged**
